version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - ENV=${ENV}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
